### ISSUE TITLE
Fix weird error that occurs from recharge system - HIDE

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/EpicRealm-Bugs#18]
```[16:39:00 WARN]: [EpicHideAndSeek] Task #81869 for EpicHideAndSeek v1.0-BETA generated an exception
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_121]
        at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_121]
        at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_121]
        at com.gmail.justbru00.epic.hideandseek.game.GameTimer.everySecond(GameTimer.java:28) ~[?:?]
        at com.gmail.justbru00.epic.hideandseek.main.Main$1.run(Main.java:54) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]```

**Comment by JustBru00** [comment]
![](http://i.imgur.com/C2P5AgQ.png)

**Comment by JustBru00** [comment]
Should be fixed with #102

**Comment by JustBru00** [comment]
ConcurrentHashMap and CopyOnWriteArrayList classes. This is the recommended approach to avoid concurrent modification exception.
